<h1>Social API Samples</h1>
<div class="floater">
<h3>Elements of Zend Framework:</h3>
<ul>
	<li><code>Zend_Service_Twitter</code></li>
	<li><code>Zend_OAuth</code></li>
</ul>
<h3>Other Tools</h3>
<ul>
	<li><code>Facebook PHP SDK</code></li>
	<li><code>Facebook Javascript SDK</code></li>
	<li><code>jQuery Javascript Library</code></li>
</ul>
</div>

<p>With social networking all the rage, I've built a few sites that
utilize these services.</p>

<p>You'll find things here such as basic twitter features: follow
people, list users, searches and more.</p>

<p>You'll also find a mini-facebook application that will show you your
friends some recent posts and allow you to update your status.</p>

<p>Social integration isn't limited to these two services by any means.
With other services offering great social APIs - foursquare, linkedin,
opensocial - Many innovative mashups can be made.</p>
