<h1>Users</h1>

<div class="floater">
<h3>Elements of Zend Framework:</h3>
<ul>
	<li><code>Zend_Acl + DEC_Acl Extensions</code></li>
	<li><code>Zend_Auth</code></li>
	<li><code>Zend_Cache</code></li>
	<li><code>Zend_Config</code></li>
	<li><code>Zend_Form</code></li>
	<li><code>Zend_Session</code></li>
</ul>
<h3>Other Tools</h3>
<ul>
	<li><code>DEC_User - A custom user model</code></li>
	<li><code>jQuery Javascript Library</code></li>
	<li><code>BeautyOfCode Highlighter</code></li>
</ul>
</div>

<p>Almost every site these days needs users to be able to
register/login/logout and interact with certain components. This brings
in Authentication and ACL setups.</p>

<p>The difference between Authentication and ACLs is simple:</p>
<ul>
	<li>Authentication tells the site who a user is.</li>
	<li>ACL (Access Control) tells the site what a user can do.</li>
</ul>

<p>Using the next few pages I'll show a simple registration process as
well as logging and logging a user out.</p>

<p>I'll demonstrate the use of Zend_Acl + Zend_Navigation as well.
You'll notice some items change in the navigation when you register and
when you login.</p>

<p><b>NOTE: </b>All Demo data will be purged from the database at random
intervals. If you return later your created accounts might not work.</p>
