<h1>What is This?</h1>

<div class="floater">
<h3>Elements of Zend Framework:</h3>
<ul>
	<li><code>Zend_Application</code></li>
	<li><code>Zend_Acl + DEC_Acl Extensions</code></li>
	<li><code>Zend_Auth</code></li>
	<li><code>Zend_Cache</code></li>
	<li><code>Zend_Config</code></li>
	<li><code>Zend_Controller_Action</code></li>
	<li><code>Zend_Controller_Router</code></li>
	<li><code>Zend_Log</code></li>
	<li><code>Zend_Navigation</code></li>
	<li><code>Zend_Session</code></li>
</ul>
<h3>Other Tools</h3>
<ul>
	<li><code>jQuery Javascript Library</code></li>
	<li><code>BeautyOfCode Highlighter</code></li>
</ul>
</div>
<p>Some people play in a sandbox. I wanted more so I built the
playground.</p>

<p>This is a demo site that I use to show-off various bits and pieces of
things that I've made for websites all over.</p>

<p>The top navigation shows you all there is on the site in nice
categories.</p>

<p>It's built on Zend Framework and uses many components of Zend
Framework as well as my own personal components that I've created over
the last few years.</p>

<p>I'll try my best to keep it 'tidy' and in working order. But, like
most playgrounds, I'm sure it'll gather some dirt over time.</p>

<h1>What this is Not?</h1>

<p>This site is not a showcase of CSS, Design, or "pretty" things.</p>

<p>This site is not a code-repository, forum for discussion, or really
anything intended for every day use.</p>

<p>Some things that get added here will have a corrensponding blog post.</p>

<p>If you have any questions about anything you can contact me <a
	href="http://darrylclarke.com/">via my blog</a>.</p>
