<form>

<input name="pants[]" value="a1"/>
<input name="pants[]" value="c11"/>
<input name="pants[]" value="b111"/>
<input name="pants[]" value="d1111"/>
<input name="pants[]" value="e11111"/>
<input name="pants[]" value="f111111"/>
<input name="pants[]" value="g2222222"/>

</form>

<script type="text/javascript">
$("input[name*='pants']").each(function() { document.write($(this).val());});
</script>