<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle('Playground'); ?>
    <?php $this->headLink()->appendStylesheet('/css/reset.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/base.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.5.custom.css'); ?>
    <?php $this->headScript()->appendFile('/js/jquery-1.4.2.min.js'); ?>
    <?php $this->headScript()->appendFile('/js/jquery-ui-1.8.5.custom.min.js'); ?>
    <?php $this->headScript()->appendFile('/js/global.js'); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
<div id="header">
    <div class="float-left"><img src="/images/slide.jpg" alt="slide" /></div>
    <h1>The Playground</h1>
    <ul>
        <li><a href="<?php echo $this->url(array('controller' => 'index'), null, true); ?>">Home</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'super'), null, true); ?>">Super</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'party'), null, true); ?>">Party</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'test'), null, true); ?>">Random BM/UI Tests</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'run-tests'), null, true); ?>">Run Unit Tests</a></li>
    </ul>
</div>
<div id="content">
    <h1><?php echo $this->title; ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>