<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle('Playground'); ?>
    <?php $this->headLink()->appendStylesheet('/css/reset.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/base.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.5.custom.css'); ?>
    <?php $this->headScript()->appendFile('/js/jquery-1.4.2.min.js'); ?>
    <?php $this->headScript()->appendFile('/js/jquery-ui-1.8.5.custom.min.js'); ?>
    <?php $this->headScript()->appendFile('/js/global.js'); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
<div id="header">
    <div class="float-left"><img src="/images/slide.jpg" alt="slide" /></div>
    <h1>The Playground</h1>
    <?php 
    
    $options = array('maxDepth' => 0);
    echo $this->navigation()->menu()->setAcl($this->acl)->renderMenu(null, $options); ?>
    <div id="subnav">
    <?php 
    $options = array('maxDepth' => 1, 'onlyActiveBranch' => true, 'renderParents' => false);
    echo $this->navigation()->menu()->setAcl($this->acl)->renderMenu(null, $options);
    ?></div>
</div>
<div id="content">
    <p><?php echo $this->navigation()->breadcrumbs(); ?></p>
    <h1><?php echo $this->title; ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
<h2 style="text-align: center;"> - THIS IS A DEMO SITE ONLY - </h2>
</body>